<div>
<img src="../Imgs/logo-numpy.svg" width="250"/>
</div>

https://numpy.org

- Abreviação para Numerical Python
- É base para muitos outros pacotes, inclusive pacotes de Machinle Learning 
- Utilizado para computação de alta performance 
- Utilizado para analise e transformação de dados
- É utilizado frequentemente em conjunto com Pandas (Próximo tema)

In [2]:
import numpy as np
import random 

#### Boolean e Seleções Avançadas

Conceito super importante no numpy e no pandas é o de máscara booleana.
<br>
Ao aplicar qualquer operador booleanoo numpy retorna um array de True e False no qual ele aplicou elemento a elemento aquele operador.

- '>'
- '<'
- '<='
- '>='
- '=='
- 'in'




In [3]:
#Array 2d
arr1 = np.array([[1,10,20,30],[1,2,50,13]])

In [4]:
arr1

array([[ 1, 10, 20, 30],
       [ 1,  2, 50, 13]])

In [5]:
arr1.ndim

2

In [6]:
arr1.shape

(2, 4)

In [11]:
#boolean simples, retorna a mesma array com True e False
boolfilter = arr1 >= 10


In [8]:
arr1 <= 10
print(arr1 == 10)
print(arr1[arr1==10])

[[False  True False False]
 [False False False False]]
[10]


In [23]:
(arr1>=10).dtype

dtype('bool')

In [12]:
#Quando colocamos cochetes ele retorna os valores nos quais o nosso boolean é verdadeiro 
print(arr1)
print(arr1>=10)
print(arr1[arr1>=10])

[[ 1 10 20 30]
 [ 1  2 50 13]]
[[False  True  True  True]
 [False False  True  True]]
[10 20 30 50 13]


In [21]:
#comparando arrays 1D
a = np.array([1,2,3,4])
b = np.array([3,8,5,6])

#funções
print(np.greater(a,b))
print(type(np.greater(a,b)))

[False False False False]
<class 'numpy.ndarray'>


In [22]:
print(a > b)
print(type(a>b))

[False False False False]
<class 'numpy.ndarray'>


In [14]:
np.less(a,b)

array([ True,  True,  True,  True])

In [15]:
np.equal(a,b)

array([False, False, False, False])

In [16]:
np.not_equal(a,b)

array([ True,  True,  True,  True])

In [27]:
# .any & .all
# 0 é coluna
np.any(arr1>5,axis=0)


array([False,  True,  True,  True])

In [25]:
np.all(arr1>5)

False

In [26]:
# 0 é coluna
# 1 é linha
np.all(arr1>5,axis=0)

array([False, False,  True,  True])

In [28]:
# 0 é coluna
# 1 é linha
np.any(arr1>10,axis=1)

array([ True,  True])

In [23]:
# 0 é coluna
# 1 é linha
np.all(arr1>10,axis=1)

array([False, False])

In [19]:
#filtro boolean and &
filtand = (arr1>10)&(arr1<=20)

In [20]:
#filtro boolean 2
arr1[filtand]

array([20, 13])

In [22]:
#podemos gerar um filtro com o resultado da nossa pergunta booleana 
filtand2 = (arr1>15)&(arr1 % 2 == 0)
arr1[filtand2]

array([20, 30, 50])

In [29]:
# filtro boolean or |
filtor = (arr1>10)|(arr1<=20)
arr1[filtor]

array([ 1, 10, 20, 30,  1,  2, 50, 13])

In [30]:
#Pegar valores do filtro 


array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [34]:
#Filtro not 
filtn = ~(arr1==10)

In [35]:
arr1[filtn]

array([ 1, 20, 30,  1,  2, 50, 13])

In [ ]:

 
# array nova sobre as condições do filtro


In [ ]:
new_arr

In [42]:
arr = np.array([x for x in range(11,40)])
print(arr)
 
# lambda + condition
# A função filter extrai elementos de um iteravel e retorna True ou False
lambda_filter = list(filter(lambda x: x>15 and x%2==0 and x%10!=0,arr))
print(lambda_filter)
# Converting new list into numpy array
new_arr = np.array(lambda_filter)
print(new_arr)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39]
[16, 18, 22, 24, 26, 28, 32, 34, 36, 38]
[16 18 22 24 26 28 32 34 36 38]


In [30]:
arr = np.array([x for x in range(11,40)])
fltr = filter(lambda x: x>15 and x%2==0 and x%10!=0,arr)
print(fltr)
ls_fltr = list(fltr)
print(ls_fltr)



[16, 18, 22, 24, 26, 28, 32, 34, 36, 38]


#### Vstack e Reorganizando Arrays

In [32]:
#reshape em uma array 1D
np.array([12,12,23,24]).reshape(2,2)

array([[12, 12],
       [23, 24]])

In [ ]:
np.array([12,12,23,24]).reshape(2,2)

In [33]:
# com -1 ele calcula por vc
np.array([12,12,23,24]).reshape(2,-1)

array([[12, 12],
       [23, 24]])

In [34]:
np.array([12,12,23,24,31,32,33,34,41,42]).reshape(-1,2)

array([[12, 12],
       [23, 24],
       [31, 32],
       [33, 34],
       [41, 42]])

In [39]:
#invert no array
a = np.array((11, 12, 21, 22, 31, 32))
b = np.invert(a)
print(b)

[-12 -13 -22 -23 -32 -33]


In [42]:
x = 9 and 14
print(type(x))

<class 'int'>


In [47]:
#Vstack em duas arrays do mesmo tamanho
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

In [49]:
print(a1)
print(a2)
vstack = np.vstack([a1,a2,a2,a2])

[1 2 3 4]
[5 6 7 8]


In [50]:
#flatten order= C(por linha), F(por coluna)
vstack.flatten('C')

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 5, 6, 7, 8])

In [52]:
vstack.flatten('F')

array([1, 5, 5, 5, 2, 6, 6, 6, 3, 7, 7, 7, 4, 8, 8, 8])

In [31]:
funcao = lambda x: x+10
funcao(20)

30

##### DIY 1

1. Crie 3 arrays 1D com 10 elementos com numeros inteiros de 1 a 10  e printe elas (dica = randint)
2. Elabore um filtro boolean na arr 1 com &, pegue os valores do array com o filtro e printe
3. Elabore um filtro boolean na arr 2 com |, pegue os valores do array com o filtro e printe
4. Faça um reshape na arr1 
5. Façã um vstack com as arr2 e arr3
6. Aplique um flatten por linha na array nova

In [28]:
arr0= np.array(np.random.randint(1,10,10))
arr0

array([9, 7, 1, 4, 4, 8, 6, 9, 5, 4])

In [33]:
arr11 = np.random.randint(11, size = 10)
arr11


array([ 5,  9,  0,  1,  8,  7,  4,  5, 10,  7])

In [12]:
# 
arr1 = np.random.randint(1,11,(10))
arr1

array([ 5,  1,  5,  6,  8, 10,  6,  2,  7,  2])

In [13]:
arr2 = np.random.randint(1,11,(10))
arr2

array([ 7,  4,  3,  5,  3, 10,  7,  6, 10, 10])

In [14]:
arr3 = np.random.randint(1,11,(10))
arr3

array([ 2,  4,  9,  4, 10,  7, 10,  1, 10,  5])

In [18]:
filtand = (arr1<=5)&(arr1!=2)
arr1[filtand]

array([5, 1, 5])

In [20]:
filtor = (arr1<=5)|(arr1==10)
arr2[filtor]

array([ 7,  4,  3, 10,  6, 10])

In [34]:
arr1_reshd = np.array(arr1).reshape(2,-1)
arr1_reshd

array([[ 5,  1,  5,  6,  8],
       [10,  6,  2,  7,  2]])

In [35]:
vstack = np.vstack([arr2,arr3])
vstack

array([[ 7,  4,  3,  5,  3, 10,  7,  6, 10, 10],
       [ 2,  4,  9,  4, 10,  7, 10,  1, 10,  5]])

In [36]:
vstack.flatten('F')

array([ 7,  2,  4,  4,  3,  9,  5,  4,  3, 10, 10,  7,  7, 10,  6,  1, 10,
       10, 10,  5])

#### Numpy Matrix

> Marizes em são obrigatoriamente elementos de duas dimensões 

In [56]:
mat1 = np.matrix([[1,2],[3,4]])
mat1

matrix([[1, 2],
        [3, 4]])

In [57]:
mat1.ndim

2

In [58]:
type(arr1)

numpy.ndarray

In [62]:
mat2 = np.matrix([[1,2,3]])
mat2

matrix([[1, 2, 3]])

In [65]:
np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
#Se eu passar uma lista simples ele cria automaticamente uma matriz de duas dim


In [ ]:
#tentando criar uma matrix maior 


In [ ]:
#bloco, linha, coluna


In [66]:
#array multi Element Wise
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a*b

array([[ 5, 12],
       [21, 32]])

In [67]:
a = np.matrix([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a*b

matrix([[19, 22],
        [43, 50]])

In [69]:
a = np.array([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
a*b

matrix([[19, 22],
        [43, 50]])

In [68]:
a = np.matrix([[1,2],[3,4]])
b = np.matrix([[5,6],[7,8]])
a*b

matrix([[19, 22],
        [43, 50]])

In [70]:
a = np.matrix([[1,2],[3,4],[5,6]])
b = np.matrix([[7,8,9],[10,11,12]])
a*b

matrix([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [71]:
a = np.matrix([[1,2],[3,4],[5,6]])
b = np.matrix([[7,8,9],[10,11,12]])
b*a

matrix([[ 76, 100],
        [103, 136]])

In [ ]:
#matriz * Dot Product


<div>
<img src="../Imgs/dotprod.jpeg" width="500"/>
</div>

In [ ]:
#Soma e subtração 


> It is no longer recommended to use the matrix class, even for linear algebra. Instead, use regular numpy arrays. The matrix class may be removed in the future. (05-2021)

##### DIY 

1. Crie uma matriz com numeros aleatorios de 1 ao 20 shape (2,2)
2. Crie um array 2D com shape (2,2)
3. Transforme a array em matrix 
4. Printe o type do array transformado
5. Faça o Dot product das matrizes


In [90]:
mtz1 = np.array(np.random.randint(1,21,4).reshape(2,2))
mtz1

array([[11, 12],
       [15, 18]])

In [82]:
mtz1 = np.matrix([[1,2],[2,1]])

In [77]:
arr2 = np.random.randint(1,21,(2,2))
arr2

array([[12,  5],
       [ 6, 17]])

In [91]:
mtz2 = np.asmatrix(arr2)
mtz2

matrix([[12,  5],
        [ 6, 17]])

In [78]:
mtz2 = np.matrix(arr2)
mtz2

matrix([[12,  5],
        [ 6, 17]])

In [79]:
print(type(mtz2))

<class 'numpy.matrix'>


In [93]:
mtz1*mtz2

matrix([[204, 259],
        [288, 381]])

In [92]:
np.dot(mtz1,mtz2)

matrix([[204, 259],
        [288, 381]])

#### Grupo

https://archive.ics.uci.edu/ml/datasets/Wine+Quality

1. Importe o mesmo dataset da aula passada 
2. Selecione as mesmas colunas Citric Acid, PH e  Alcohol
3. Faça um filtro booleano com os vinhos com:
    - um valor maior ou igual a 6 de Alcohol
    - um valor de PH menor do que 3
    - um valor de Citric Acid maior do que .20
4. Faça um novo array com esses dados 
5. Quantos vinhos tem a nossa seleção?
6. Quantos vinhos deixamos de fora?
7. Faça um outro filtro segundo a sua criatividade 
8. Qual a sua conclusão?

array([[ 7, 16],
       [ 7, 12]])