<div>
<img src="Imgs/logo-numpy.svg" width="250"/>
</div>

https://numpy.org

- Abreviação para Numerical Python
- É base para muitos outros pacotes, inclusive pacotes de Machinle Learning 
- Utilizado para computação de alta performance 
- Utilizado para analise e transformação de dados
- É utilizado frequentemente em conjunto com Pandas (Próximo tema)

Curiosidade sobre Numpy
https://numpy.org/case-studies/blackhole-image/

In [2]:
import numpy as np

#### Conceitos principais

In [ ]:
#numpy.ndarray VS Lists
list1 = [4,2,5,6,10]
array1 = np.array(list1)
print(f'List: {list1}')
print(type(list1))
print(list1)
print(type(list1[1]))
print(type(list1[4]))
print('\n')
print(f'Numpy array: {array1}')
print(f'Type: {type(array1)}')
print(array1)
print(type(array1[0]))
print(type(array1[3]))


In [ ]:
# Soma de um numero na lista e no nparray
arr + 2

In [ ]:
list1 + 2

>Todos os itens de um array devem ser do mesmo tipo, diferentemente os itens de uma lista. Segue!

- i - integer
- b - boolean
- U - unsigned integer (Inteiros que não tem simbolos de + ou - associados )
- f - float
- c - complex float (Numeros Imaginarios)
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string

In [ ]:
#Testes com diferentes tipos
#Str>Float>Int
list2 = [[2,3,4,4],[3,40,100,0]]

In [ ]:
#dtype param 


In [ ]:
#ndim, shape, size, dtype


In [ ]:
#astype


In [6]:
#zeros = array feita de zeros

#ones - array feita de qualquer numero

#empty - array dada um tamanho e tipo determinado com valores randomicos
npempty = np.empty((2,2),dtype='int')
print(npempty)
#full - parecida a ones porem mais "elegante"

#fulllike - cria um array baseada em uma
# existente com outro numero dado
# nplike = np.full_like(npfull,4)
# print(nplike)
# arange - cria um array com elementos separados por um step
nparange = np.arange(0,10,5)
print(nparange)
#copias do array 
array = np.array([1,2,3])
arraycopy = array.copy()
print(arraycopy)
print(arraycopy)

[[ -495339213  1951276594]
 [ -419191370 -1428299268]]
[0 5]
[1 2 3]
[1 2 3]


#### Operações entre ndarrays

> Numpy foi feito para manipular e realizar operações vetorizadas em grande escala, com velocidade

In [ ]:
#creating random arrays  = np.random.random_sample retorna array do tamanho pedido com numeros entre 0.0, 1.0

In [ ]:
np.random.random_sample((3, 3))

In [ ]:
#multipy, divide, add, subtract


##### DIY

Ex 1
1) Transforme a duas listas em duas arrays diferentes arr1 e arr2.
2) Verifique o dtype dos array
3) Transforme os dois array em float
4) Compare as duas arrays e mostre os indices dos elementos que são iguais(dica : where)
5) Retorne os numeros do array que são iguais usando o output do paso 4 dica subsetting

In [13]:
list_1 = [1,2,3,4,5]
list_2 = [1,3,2.2,4,5]


In [19]:
arr1 = np.array(list_1)
arr2 = np.array(list_2)

In [20]:
arr1 = arr1.astype('f')
arr2 = arr2.astype('f')

In [21]:
print(arr1)
print(arr2)

[1. 2. 3. 4. 5.]
[1.  3.  2.2 4.  5. ]


In [22]:
np.where(arr1==arr2)

(array([0, 3, 4], dtype=int64),)

In [23]:
arr1[[0,3,4]]

array([1., 4., 5.], dtype=float32)

#### Indexação, Slicing

In [24]:
array = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])


In [25]:
array.shape

(2, 7)

In [29]:
#seleção por index [linha, coluna]
#numero especifico
print(array[0,4])
#numero especifico negativo
print(array[-1,-2])

# : é chamado de slicing [startindex:endindex:stepsize]
#primera linha
print(array[0,:])
#todos os elementos da 2 coluna
print(array[:,2])
#elemento especificos com step
print(array[:,1:6:2])

5
13
[1 2 3 4 5 6 7]
[ 3 10]
[[ 2  4  6]
 [ 9 11 13]]


> conseguimos mudar também elementos especificos de uma array usando index e slicing

In [33]:
#trocando um numero especifico
array[1,4] = 7
print(array)
#trocar coluna inteira 
array[:,2] = 5
print(array)
#voltar os valores originais 
array[:,2] = [3,10]
print(array)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11  7 13 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11  7 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11  7 13 14]]


#### DIY

Ex 2
1) Gere uma array com 3 dimensões com shape. (2,2,2)
2) Printe o ndim da array e o shape
3) Retire um elemento especifico [bloco][linha][coluna]



In [34]:
array3d= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])


(2, 2, 2)


In [35]:
#print array
print(array3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
#print ndim
print(array3d.ndim)

3


In [37]:
#print shape
print(array3d.shape)

(2, 2, 2)


In [36]:
#print elemento
print(array3d[0,1,1])

4


##### Dica

O array 3D é um conjunto de arrays de duas dimensões, "um array de arrays de arrays", os elementos são acessados para um indice para linha, um para coluna um para o bloco ( Parecido com um cubo). Tem apliações em diversas areas como: Jogos, Data Wharehouses, Analise de dados entre outros. 

Ordem [bloco][linha][coluna]

<div>
<img src="Imgs/arrays.png" width="500"/>
</div>
<img src="Imgs/formato3d.png" width="500"/>

#### Transposição, Stacking e Redimensionamento

<img src="Imgs/transpose.png" width="500"/>

In [23]:
array = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [24]:
array.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])

In [26]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                    [[10,11,12],[13,14,15],[16,17,18]],
                    [[19,20,21],[22,23,24],[25,26,27]]])

print(array3d)
print(array3d.T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1 10 19]
  [ 4 13 22]
  [ 7 16 25]]

 [[ 2 11 20]
  [ 5 14 23]
  [ 8 17 26]]

 [[ 3 12 21]
  [ 6 15 24]
  [ 9 18 27]]]


#### Estatistica

In [43]:
stats = np.array([[1,8,3],[4,5,6]])
print(stats)

[[1 8 3]
 [4 5 6]]


In [41]:
#minimo do nosso array
np.min(stats)

1

In [44]:
#maximo do nosso array
np.max(stats)

8

In [45]:
#minima por linha
np.min(stats, 1)

array([1, 4])

In [10]:
# array3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                    [[10,11,12],[13,14,15],[16,17,18]],
                    [[19,20,21],[22,23,24],[25,26,27]]])
print(array3d)
print(np.min(array3d, 0))
print(np.min(array3d, 1))
print(np.min(array3d, 2))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 11 12]
 [19 20 21]]
[[ 1  4  7]
 [10 13 16]
 [19 22 25]]


In [15]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                    [[10,11,12],[13,14,15],[16,17,18]],
                    [[19,20,21],[22,23,24],[25,26,27]]])
print(array3d[:,:,1])
print(array3d[:,2])
print(np.max(array3d[:,2]))
print(np.max(array3d[:,2],0))
print(np.max(array3d[:,2],1))
print(np.max(array3d[:,2]))

[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
[[ 7  8  9]
 [16 17 18]
 [25 26 27]]
27
[25 26 27]
[ 9 18 27]
27


In [22]:
array3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                    [[10,11,12],[13,14,15],[16,17,18]],
                    [[19,20,21],[22,23,24],[25,26,27]]])
print(array3d[:3:2]) # print(array3d[[0,2]])
print(array3d[:3:2, 1])
print(np.min(array3d[:3:2, 1]))

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[ 4  5  6]
 [22 23 24]]
4


In [46]:
#minima por coluna
np.min(stats, 0)

array([1, 5, 3])

In [50]:
#maximo de uma coluna especifica
np.min(stats[:,1],0)

5

#### DIY - Grupos

https://archive.ics.uci.edu/ml/datasets/Wine+Quality

In [28]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv'

In [29]:
wine_arr = np.genfromtxt(url, delimiter=';', usecols=[2,8,11], skip_header = True)
wine_arr

array([[0.  , 3.51, 5.  ],
       [0.  , 3.2 , 5.  ],
       [0.04, 3.26, 5.  ],
       ...,
       [0.13, 3.42, 6.  ],
       [0.12, 3.57, 5.  ],
       [0.47, 3.39, 6.  ]])

DICA : Procure por nan e substitua por 0 (dica: is_nan e nan_to_num)m

https://numpy.org/devdocs/user/basics.io.genfromtxt.html
1) Verifique a url e veja quais são as colunas do arquivo
2) Veja qual é o delimiter do arquivo ',' , ':', ';'
3) Selecione as colunas (param usecols) Citric Acid, PH e  Alcohol
4) Mostre o array e as caracteristicas dele ndim, shape, dype
5) Procure o maximo e minimo da coluna PH 
6) Obtenha a media da coluna Alcohol

In [30]:
import numpy as np
with open('winequality-red.csv', 'r') as arquivo:
    wine_arr = np.genfromtxt(arquivo, delimiter=';', usecols=(2,8,10), skip_header=1)
# 2 Citric Acid
# 8 PH
# 10 Alcool

print(np.min(wine_arr[:,1]))
print(np.max(wine_arr[:,1]))


2.74
4.01


In [ ]:
#Import data
wine_arr = np.genfromtxt()

In [31]:
#Show array
print(wine_arr)

print(wine_arr.ndim)

print(wine_arr.shape)

print(wine_arr.dtype)

[[ 0.    3.51  9.4 ]
 [ 0.    3.2   9.8 ]
 [ 0.04  3.26  9.8 ]
 ...
 [ 0.13  3.42 11.  ]
 [ 0.12  3.57 10.2 ]
 [ 0.47  3.39 11.  ]]
2
(1599, 3)
float64


In [42]:
# Max Min Avg PH
print(np.min(wine_arr[1:,1]))
print(np.max(wine_arr[1:,1]))
print(np.average(wine_arr[1:,1]))
print(np.std(wine_arr[1:,1]))

2.74
4.01
3.3109887359198997
0.15430622682778028


In [43]:
# Max Min Avg Alcool
print(np.min(wine_arr[1:,2]))
print(np.max(wine_arr[1:,2]))
print(np.average(wine_arr[1:,2]))
print(np.std(wine_arr[1:,2]))

8.4
14.9
10.423623279098875
1.0653600835210026


In [44]:
# Max Min Avg Acido Citrico
print(np.min(wine_arr[1:,0]))
print(np.max(wine_arr[1:,0]))
print(np.average(wine_arr[1:,0]))
print(np.std(wine_arr[1:,0]))

0.0
1.0
0.2711451814768461
0.1946830875536191


In [12]:
#Mean
np.average(wine_arr[1:,2])

10.423623279098875

#### Extra

1) Faça um for loop que itere por todos os elementos de uma array de 3 dimensões

In [17]:
for b in range(2):
    for c in range(2):
        for l in range(2):
            print(f'Bloco {b}, Linha {l}, - Elemento: {array3d[b][l][c]}')

Bloco 0, Linha 0, - Elemento: 1
Bloco 0, Linha 1, - Elemento: 3
Bloco 0, Linha 0, - Elemento: 2
Bloco 0, Linha 1, - Elemento: 4
Bloco 1, Linha 0, - Elemento: 5
Bloco 1, Linha 1, - Elemento: 7
Bloco 1, Linha 0, - Elemento: 6
Bloco 1, Linha 1, - Elemento: 8
