<div>
<img src="../Imgs/logo-numpy.svg" width="250"/>
</div>

https://numpy.org

- Abreviação para Numerical Python
- É base para muitos outros pacotes, inclusive pacotes de Machinle Learning 
- Utilizado para computação de alta performance 
- Utilizado para analise e transformação de dados
- É utilizado frequentemente em conjunto com Pandas (Próximo tema)

In [1]:
import numpy as np
import random 

#### Boolean e Seleções Avançadas

Conceito super importante no numpy e no pandas é o de máscara booleana.
<br>
Ao aplicar qualquer operador booleanoo numpy retorna um array de True e False no qual ele aplicou elemento a elemento aquele operador.

- '>'
- '<'
- '<='
- '>='
- '=='
- 'in'




In [ ]:
#Array 2d


In [ ]:
#boolean simples, retorna a mesma array com True e False


In [ ]:
#Quando colocamos cochetes ele retorna os valores nos quais o nosso boolean é verdadeiro 


In [ ]:
#comparando arrays 1D


#funções


In [ ]:
# .any & .all
#coluna

#linea


In [ ]:
#filtro boolean and &


In [ ]:
#filtro boolean 2


In [ ]:
#podemos gerar um filtro com o resultado da nossa pergunta booleana 


In [ ]:
# filtro boolean or |


In [ ]:
#Pegar valores do filtro 


In [ ]:
#Filtro not 


In [ ]:

 
# array nova sobre as condições do filtro


In [ ]:
new_arr

In [ ]:

 
# lambda + condition
# A função filter extrai elementos de um iteravel e retorna True ou False

 
# Converting new list into numpy array


#### Vstack e Reorganizando Arrays

In [ ]:
#reshape em uma array 1D


In [ ]:
#invert no array


In [ ]:
#Vstack em duas arrays do mesmo tamanho


In [ ]:
#flatten order= C(por coluna), F(por lina)


##### DIY 1

1. Crie 3 arrays 1D com 10 elementos com numeros inteiros de 1 a 10  e printe elas (dica = randint)
2. Elabore um filtro boolean na arr 1 com &, pegue os valores do array com o filtro e printe
3. Elabore um filtro boolean na arr 2 com |, pegue os valores do array com o filtro e printe
4. Faça um reshape na arr1 
5. Façã um vstack com as arr2 e arr3
6. Aplique um flatten por linha na array nova

In [22]:
array1 = np.random.randint(11, size = 10)
array2 = np.random.randint(11, size = 10)
array3 = np.random.randint(11, size = 10)
print(array1)
print(array2)
print(array3)

[7 1 7 6 9 8 2 4 9 6]
[1 0 7 2 3 9 4 4 1 9]
[4 5 4 3 5 9 4 7 9 0]


In [29]:
array1_filter = (array1 > 5) & (array1 <= 10)
print(array1[array1_filter])


[7 7 6 9 8 9 6]


In [30]:
array1_filter = (array1 > 6) | (array1 == 10)
print(array1[array1_filter])


[7 7 9 8 9]


In [25]:
array1.reshape(2,5)

array([[7, 1, 7, 6, 9],
       [8, 2, 4, 9, 6]])

In [26]:
arrays_vstack = np.vstack([array1, array2])
print(arrays_vstack)

[[7 1 7 6 9 8 2 4 9 6]
 [1 0 7 2 3 9 4 4 1 9]]


In [31]:
arrays_vstack.flatten('F')

array([7, 1, 1, 0, 7, 7, 6, 2, 9, 3, 8, 9, 2, 4, 4, 4, 9, 1, 6, 9])

#### Numpy Matrix

> Marizes em são obrigatoriamente elementos de duas dimensões 

In [ ]:
#Se eu passar uma lista simples ele cria automaticamente uma matriz de duas dim


In [ ]:
#tentando criar uma matrix maior 


In [ ]:
#bloco, linha, coluna


In [ ]:
#array multi Element Wise


In [ ]:
#matriz * Dot Product


<div>
<img src="../Imgs/dotprod.jpeg" width="500"/>
</div>

In [ ]:
#Soma e subtração 


> It is no longer recommended to use the matrix class, even for linear algebra. Instead, use regular numpy arrays. The matrix class may be removed in the future. (05-2021)

##### DIY 

1. Crie uma matriz com numeros aleatorios de 1 ao 20 shape (2,2)
2. Crie um array 2D com shape (2,2)
3. Transforme a array em matrix 
4. Printe o type do array transformado
5. Faça o Dot product das matrizes


#### Grupo

https://archive.ics.uci.edu/ml/datasets/Wine+Quality

1. Importe o mesmo dataset da aula passada 
2. Selecione as mesmas colunas Citric Acid, PH e  Alcohol
3. Faça um filtro booleano com os vinhos com:
    - um valor maior ou igual a 6 de Alcohol
    - um valor de PH menor do que 3
    - um valor de Citric Acid maior do que .20
4. Faça um novo array com esses dados 
5. Quantos vinhos tem a nossa seleção?
6. Quantos vinhos deixamos de fora?
7. Faça um outro filtro segundo a sua criatividade 
8. Qual a sua conclusão?

In [77]:
#Import data
with open('winequality-red.csv', "r") as arquivo:
    wine_arr = np.genfromtxt(arquivo, delimiter=";", usecols=(2, 8, 10), skip_header=1)
    wine_arr
    #wine_arr[0,:]=0
    #print(wine_arr)


print('Quantidade original:', len(wine_arr))
filtro = (wine_arr[:, 2] >= 6 ) & (wine_arr[:, 1] < 3) & (wine_arr[:, 0] > .20)
#print(filtro)
wine_arr_filtrado = wine_arr[filtro]
qtde_vinhos= len(wine_arr_filtrado)
qtde_fora = len(wine_arr[~filtro])
print('Vinhos de filtrados:' , qtde_vinhos)
print('Vinhos de fora:' , qtde_fora)
print(wine_arr_filtrado)

Quantidade original: 1599
[[ 0.28  2.93  9.9 ]
 [ 0.28  2.93  9.9 ]
 [ 0.29  2.93  9.8 ]
 [ 1.    2.74  9.4 ]
 [ 0.63  2.99 10.2 ]
 [ 0.72  2.88  9.8 ]
 [ 0.76  2.95 11.2 ]
 [ 0.54  2.98  9.2 ]
 [ 0.74  2.86  8.4 ]
 [ 0.49  2.92 11.1 ]
 [ 0.49  2.92 11.1 ]
 [ 0.49  2.92 11.1 ]
 [ 0.49  2.98  9.9 ]
 [ 0.55  2.98  9.4 ]
 [ 0.39  2.89  9.6 ]
 [ 0.65  2.98 14.9 ]
 [ 0.39  2.89  9.6 ]
 [ 0.59  2.92 10.5 ]
 [ 0.45  2.94  9.2 ]
 [ 0.45  2.94  9.2 ]
 [ 0.3   2.94  9.5 ]
 [ 0.3   2.99 10.2 ]
 [ 0.37  2.89 12.7 ]
 [ 0.37  2.89 12.7 ]
 [ 0.54  2.98 11.8 ]
 [ 0.26  2.94 10.2 ]
 [ 0.68  2.9   9.1 ]]


In [84]:
filtro_criativo = (wine_arr[:, 2] >= 11 ) & (wine_arr[:, 1] < 3) #& (wine_arr[:, 0] > .20)
wine_arr_novo_filtro = wine_arr[filtro_criativo]
print(wine_arr_novo_filtro)

[[ 0.76  2.95 11.2 ]
 [ 0.49  2.92 11.1 ]
 [ 0.49  2.92 11.1 ]
 [ 0.49  2.92 11.1 ]
 [ 0.65  2.98 14.9 ]
 [ 0.37  2.89 12.7 ]
 [ 0.37  2.89 12.7 ]
 [ 0.54  2.98 11.8 ]]
