<div>
<img src="../Imgs/logo-numpy.svg" width="250"/>
</div>

https://numpy.org

- Abreviação para Numerical Python
- É base para muitos outros pacotes, inclusive pacotes de Machinle Learning 
- Utilizado para computação de alta performance 
- Utilizado para analise e transformação de dados
- É utilizado frequentemente em conjunto com Pandas (Próximo tema)

In [74]:
import numpy as np
import random 

#### Boolean e Seleções Avançadas

Conceito super importante no numpy e no pandas é o de máscara booleana.
<br>
Ao aplicar qualquer operador booleanoo numpy retorna um array de True e False no qual ele aplicou elemento a elemento aquele operador.

- '>'
- '<'
- '<='
- '>='
- '=='
- 'in'




In [41]:
#Array 2d
arr1 = np.array([[1, 10, 20, 30],[1,2,50,13]])
print(arr1)

[[ 1 10 20 30]
 [ 1  2 50 13]]


In [24]:
#boolean simples, retorna a mesma array com True e False
arr1 >10

array([[False, False,  True,  True],
       [False, False,  True,  True]])

In [25]:
#Quando colocamos cochetes ele retorna os valores nos quais o nosso boolean é verdadeiro 
arr1[arr1 > 10]

array([20, 30, 50, 13])

In [ ]:
#comparando arrays 1D
a = np.array([1,2,3,4]) 
b = np.array([3,8,5,6])

#funções
np.greater(a, b)
np.less(a, b)
np.equal(a, b)
np.not_equal(a, b)

In [13]:
# .any & .all
#coluna
np.any(arr1 > 10, axis=0)
#linea
np.any(arr1 > 10, axis=1)

array([False,  True])

In [42]:
#filtro boolean and &
filtand = (arr1 > 10) & (arr1 <= 20)
filtand

array([[False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
#filtro boolean 2
filtand2 = (arr > 15) & (arr % 2 == 0)

In [43]:
#podemos gerar um filtro com o resultado da nossa pergunta booleana 
arr1[filtand]

array([20, 13])

In [44]:
# filtro boolean or |
filtor = (arr1 > 10) | (arr1 <= 20)
filtor

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [45]:
#Pegar valores do filtro 
arr1[filtor]

array([ 1, 10, 20, 30,  1,  2, 50, 13])

In [27]:
#Filtro not 
filt = ~(arr1 == 1) 

In [28]:
filt

array([[False,  True,  True,  True],
       [False,  True,  True,  True]])

In [47]:
filtro2 = (arr1 > 15) & (arr1 % 2 == 0)
 
# array nova sobre as condições do filtro
new_arr = arr1[filtro2]

In [48]:
new_arr

array([20, 30, 50])

In [33]:
arr = np.array([x for x in range(11, 40)])
 
print(arr)
 
# lambda + condition
# A função filter extrai elementos de um iteravel e retorna True ou False
new_arr = list(filter(lambda x: x > 15 and x % 2 == 0 and x % 10 != 0, arr))
 
# Converting new list into numpy array
new_arr = np.array(new_arr)

Original array
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39]


#### Vstack e Reorganizando Arrays

In [50]:
#reshape em uma array 1D
np.array([12, 12, 23, 34]).reshape(2, 2)

array([[12, 12],
       [23, 34]])

In [30]:
#invert no array
a = np.array((12, 12, 23, 34, 2))
b = np.invert(a)
print(b)

[-13 -13 -24 -35  -3]


In [69]:
#Vstack em duas arrays do mesmo tamanho
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print(a1)
print(a2)
vstack = np.vstack([a1,a2])

[1 2 3 4]
[5 6 7 8]


In [71]:
a1.shape

(4,)

In [56]:
vstack2 = np.vstack([a1,a2,a2,a2])

In [60]:
vstack2

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [66]:
#flatten order= C(por coluna), F(por lina)
vstack2.flatten('C')
vstack2.flatten('F')

array([1, 5, 5, 5, 2, 6, 6, 6, 3, 7, 7, 7, 4, 8, 8, 8])

##### DIY 1

1. Crie 3 arrays 1D com 10 elementos com numeros inteiros de 1 a 10  e printe elas (dica = randint)
2. Elabore um filtro boolean na arr 1 com &, pegue os valores do array com o filtro e printe
3. Elabore um filtro boolean na arr 2 com |, pegue os valores do array com o filtro e printe
4. Faça um reshape na arr1 
5. Façã um vstack com as arr2 e arr3
6. Aplique um flatten por linha na array nova

#### Numpy Matrix

> Marizes em são obrigatoriamente elementos de duas dimensões 

In [80]:
mat1 = np.matrix([[1, 2],[3, 4]])

In [85]:
arr1 = np.array([5,6,7,8])

In [86]:
type(arr1)

numpy.ndarray

In [84]:
type(mat1)

numpy.matrix

In [87]:
mat1.ndim

2

In [89]:
#Se eu passar uma lista simples ele cria automaticamente uma matriz de duas dim
mat2 = np.matrix([1, 2, 3])

In [90]:
mat2.ndim

2

In [91]:
#tentando criar uma matrix maior 
np.matrix([[[1, 2], [3, 4]], 
          [[5, 6], [7, 8]], 
          [[9, 10], [11, 12]]])

ValueError: matrix must be 2-dimensional

In [94]:
arr2 = np.array([[[1, 2], [3, 4]], 
          [[5, 6], [7, 8]], 
          [[9, 10], [11, 12]]])

In [96]:
#bloco, linha, coluna
print(arr2.ndim)
print(arr2.shape)

3
(3, 2, 2)


In [97]:
#array multi Element Wise
a = np.array([[1, 2], 
             [3, 4]])
b = np.array([[5, 6], 
             [8, 9]])
print(a * b)

[[ 5 12]
 [24 36]]


In [114]:
#matriz * Dot Product
c = np.matrix([[1, 2], 
              [3, 4]])
d = np.matrix([[5, 6], 
              [8, 9]])
print(c)
print(d)
print(c * d)

[[1 2]
 [3 4]]
[[5 6]
 [8 9]]
[[21 24]
 [47 54]]


<div>
<img src="../Imgs/dotprod.jpeg" width="500"/>
</div>

In [112]:
#Soma e subtração 
print(c+d)
print(d-c)

[[ 6  8]
 [11 13]]
[[4 4]
 [5 5]]


> It is no longer recommended to use the matrix class, even for linear algebra. Instead, use regular numpy arrays. The matrix class may be removed in the future. (05-2021)

##### DIY 

1. Crie uma matriz com numeros aleatorios de 1 ao 20 shape (2,2)
2. Crie um array 2D com shape (2,2)
3. Transforme a array em matrix 
4. Printe o type do array transformado
5. Faça o Dot product das matrizes


#### Grupo

https://archive.ics.uci.edu/ml/datasets/Wine+Quality

1. Importe o mesmo dataset da aula passada 
2. Selecione as mesmas colunas Citric Acid, PH e  Alcohol
3. Faça um filtro booleano com os vinhos com:
    - um valor maior ou igual a 6 de Alcohol
    - um valor de PH menor do que 3
    - um valor de Citric Acid maior do que .20
4. Faça um novo array com esses dados 
5. Quantos vinhos tem a nossa seleção?
6. Quantos vinhos deixamos de fora?
7. Faça um outro filtro segundo a sua criatividade 
8. Qual a sua conclusão?