## Exercícios Aulas 1 a 4
Prof Roger Rendón

In [3]:
#Imports
import numpy as np
import pandas as pd

#### Numpy.

In [33]:
#1. Gere uma array randomica de 10 elementos com duas dimensões, e explore o array (ndim, dtype e shape).
# np.random.random_sample((5,2))*11.astype('int)
arr = np.random.randint(0,10,10).reshape(2,-1)
arr


array([[4, 5, 9, 3, 9],
       [0, 7, 5, 5, 6]])

In [13]:
arr.ndim

2

In [15]:
arr.dtype

dtype('float64')

In [16]:
arr.shape

(2, 5)

In [18]:
#2. Verifique os elementos da array e veja se tem valores NaN e transforme os valores NaN pra número
a =  np.array([1, 0, np.nan, 6.0])

In [21]:
np.isnan(a)

array([False, False,  True, False])

In [24]:
a = np.nan_to_num(a)
a

array([1., 0., 0., 6.])

In [ ]:
#3. Gere duas arrays de uma dimensão com 10 elementos cada, valores entre 1 e 50. 
    # Faça comparações entre as duas matrizes ( >, <, equal)

In [38]:
arr1 = np.random.randint(1,51,10)
arr2 = np.random.randint(1,51,10)

In [27]:
arr1

array([42, 29, 13, 28, 50, 50, 25, 50, 34, 30])

In [28]:
arr2

array([ 2, 17, 47, 27, 36, 25, 48, 45, 23, 37])

In [29]:
arr1 > arr2

array([ True,  True, False,  True,  True,  True, False,  True,  True,
       False])

In [39]:
arr1[arr1 > arr2]

array([29, 31, 50, 36, 40, 40, 47, 43])

In [30]:
arr1 < arr2

array([False, False,  True, False, False, False,  True, False, False,
        True])

In [40]:
arr1[arr1 < arr2]

array([ 1, 10])

In [31]:
arr1 == arr2

array([False, False, False, False, False, False, False, False, False,
       False])

In [41]:
arr1[arr1 == arr2]

array([], dtype=int32)

In [32]:
arr1 != arr2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [42]:
arr1[arr1 != arr2]

array([29, 31,  1, 10, 50, 36, 40, 40, 47, 43])

In [5]:
#4. Faça uma array com aragne de 12 elementos e de o reshape correto nele. 
    # Salve sua array em um arquivo de texto (Dica = Save Text and Headers)

In [6]:
arange_arr = np.arange(5,125,10)
arange_arr

array([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105, 115])

In [7]:
len(arange_arr)

12

In [55]:
# O que seria o "reshape correto"????
arrange_arr_reshape=arange_arr.reshape(4,-1)

In [80]:
np.savetxt('arange_arr.txt', arrange_arr_reshape, delimiter=',', header='0,1,2', fmt = '%f', comments="")

In [77]:
# o txt pode ser importado no pd com os headers by Gu
df_arr = pd.read_csv('arange_arr.txt', sep=',')

In [78]:
df_arr

0      1      2
0   5.0   15.0   25.0
1  35.0   45.0   55.0
2  65.0   75.0   85.0
3  95.0  105.0  115.0

In [ ]:
#5. Carregue o arquvio da array anterior e faça uma subseleções:
    #Elemento na linha 1 coluna 1 
    #Elementos na coluna 2
    #Elementos na linha 2 e escolha o maximo valor dessa seleção
    #Uma array nova com o resultado de uma seleção complexa ex. (arr1 > 3) & (arr1 % 2 == 0)
    

In [69]:
load_arr = np.loadtxt('arange_arr.txt', delimiter=',')

In [70]:
load_arr

array([[  0.,   1.,   2.],
       [  5.,  15.,  25.],
       [ 35.,  45.,  55.],
       [ 65.,  75.,  85.],
       [ 95., 105., 115.]])

In [71]:
#5. Carregue o arquvio da array anterior e faça uma subseleções:
load_arr_skphdr = np.loadtxt('arange_arr.txt', delimiter=',', skiprows=1)

In [72]:
load_arr_skphdr

array([[  5.,  15.,  25.],
       [ 35.,  45.,  55.],
       [ 65.,  75.,  85.],
       [ 95., 105., 115.]])

In [86]:
#Elemento na linha 1 coluna 1 
load_arr_skphdr[1,1]

45.0

In [87]:
#Elementos na coluna 2
load_arr_skphdr[:,2]

array([ 25.,  55.,  85., 115.])

In [88]:
#Elementos na linha 2 e escolha o maximo valor dessa seleção
load_arr_skphdr[2]

array([65., 75., 85.])

In [89]:
#Uma array nova com o resultado de uma seleção complexa ex. (arr1 > 3) & (arr1 % 2 == 0)
load_arr_skphdr[2].max()

85.0

In [94]:
#Uma array nova com o resultado de uma seleção complexa ex. (arr1 > 3) & (arr1 % 2 == 0)
filtro1 = load_arr_skphdr >50
filtro1


array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [95]:
filtro2 = load_arr_skphdr % 3 == 0
filtro2

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [96]:
vetor_selecao = load_arr_skphdr[filtro1&filtro2]
vetor_selecao

array([ 75., 105.])

In [106]:
#6. Gere duas arrays em formato de matriz e faça um dot product nela 
arr_mtz_1 = np.random.randint(0,10,9).reshape(3,-1)
arr_mtz_2 = np.random.randint(0,10,9).reshape(3,-1)


In [107]:
arr_mtz_1

array([[2, 8, 7],
       [2, 1, 0],
       [3, 8, 9]])

In [108]:
arr_mtz_2

array([[8, 4, 6],
       [4, 7, 5],
       [9, 6, 6]])

In [109]:
np.matmul(arr_mtz_1,arr_mtz_2)

array([[111, 106,  94],
       [ 20,  15,  17],
       [137, 122, 112]])

In [110]:
np.dot(arr_mtz_1,arr_mtz_2)

array([[111, 106,  94],
       [ 20,  15,  17],
       [137, 122, 112]])

#### Pandas

In [ ]:
#1. Faça uma pandas Series com valores inteiros randomicos de tamanho 30 de numeros entre 5 e 15
    # Divida sua serie em duas partes e gere duas series novas 
    # Adicione 5 valores a cada serie e mantenha os dois elementos como series
    # Conte as aparições de cada elemento da Serie
    # Faça comparações booleanas entre as das series
    # Junte as duas series em um dataframe
    # Rename nas colunas utilizando inplace 
    # Explore seu novo DataFrame

In [129]:
# Divida sua serie em duas partes e gere duas series novas 
pdSeries = pd.Series(np.random.randint(5,16,30))
pdSeries_1 = pdSeries[0:15].copy().reset_index(drop=True)
pdSeries_2 = pdSeries[15:30].copy().reset_index(drop=True)

In [ ]:
pdSeries

In [131]:
pdSeries_1

0     10
1     13
2     14
3     13
4     15
5      7
6      6
7     15
8      6
9     10
10     7
11     5
12    11
13    10
14    15
dtype: int32

In [132]:
pdSeries_2

0     13
1     15
2     14
3      9
4     12
5     13
6     11
7     15
8      5
9     11
10     9
11     8
12    12
13    12
14     7
dtype: int32

In [133]:
# Adicione 5 valores a cada serie e mantenha os dois elementos como series
add_1 = pd.Series(np.random.randint(5,16,5))
add_2 = pd.Series(np.random.randint(5,16,5))
concatS1 = pd.concat([pdSeries_1, add_1]).reset_index(drop=True)
concatS2 = pd.concat([pdSeries_2, add_2]).reset_index(drop=True)

In [134]:
concatS1

0     10
1     13
2     14
3     13
4     15
5      7
6      6
7     15
8      6
9     10
10     7
11     5
12    11
13    10
14    15
15    12
16    10
17     5
18     6
19    15
dtype: int32

In [135]:
concatS2

0     13
1     15
2     14
3      9
4     12
5     13
6     11
7     15
8      5
9     11
10     9
11     8
12    12
13    12
14     7
15     9
16    14
17    15
18    13
19     9
dtype: int32

In [144]:
# Conte as aparições de cada elemento da Serie
concatS1.value_counts()

10    4
15    4
6     3
13    2
7     2
5     2
14    1
11    1
12    1
dtype: int64

In [145]:
concatS2.value_counts()

9     4
13    3
15    3
12    3
14    2
11    2
5     1
8     1
7     1
dtype: int64

In [136]:
# Faça comparações booleanas entre as das series
filter_1 = concatS1 > concatS2
filter_2 = concatS1 < concatS2
filter_3 = concatS1 == concatS2
filter_4 = concatS1 != concatS2

In [ ]:
display(filter_1)
display(filter_2)
display(filter_3)
display(filter_4)

In [138]:
concatS1[filter_1]

3     13
4     15
8      6
14    15
15    12
19    15
dtype: int32

In [139]:
concatS1[filter_2]

0     10
1     13
5      7
6      6
9     10
10     7
11     5
12    11
13    10
16    10
17     5
18     6
dtype: int32

In [140]:
concatS1[filter_3]

2    14
7    15
dtype: int32

In [141]:
concatS1[filter_4]

0     10
1     13
3     13
4     15
5      7
6      6
8      6
9     10
10     7
11     5
12    11
13    10
14    15
15    12
16    10
17     5
18     6
19    15
dtype: int32

In [153]:
# Junte as duas series em um dataframe
df = pd.DataFrame([concatS1, concatS2]).T

In [ ]:
df

In [155]:
# Rename nas colunas utilizando inplace 
df.rename(columns={0:"coluna_0",1:"coluna_1"}, inplace=True)

In [157]:
df.head()

coluna_0  coluna_1
0        10        13
1        13        15
2        14        14
3        13         9
4        15        12

In [158]:
# Explore seu novo DataFrame
df.head()

coluna_0  coluna_1
0        10        13
1        13        15
2        14        14
3        13         9
4        15        12

In [163]:
df.tail()

coluna_0  coluna_1
15        12         9
16        10        14
17         5        15
18         6        13
19        15         9

In [160]:
df.dtypes

coluna_0    int32
coluna_1    int32
dtype: object

In [161]:
df.value_counts()

coluna_0  coluna_1
5         8           1
          15          1
15        12          1
          9           1
          7           1
14        14          1
13        15          1
          9           1
12        9           1
11        12          1
10        14          1
          13          1
          12          1
          11          1
7         13          1
          9           1
6         13          1
          11          1
          5           1
15        15          1
dtype: int64

In [162]:
df.columns

Index(['coluna_0', 'coluna_1'], dtype='object')

In [164]:
df.shape

(20, 2)

In [166]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   coluna_0  20 non-null     int32
 1   coluna_1  20 non-null     int32
dtypes: int32(2)
memory usage: 288.0 bytes


In [167]:
df.describe()

coluna_0   coluna_1
count  20.000000  20.000000
mean   10.250000  11.300000
std     3.654485   2.867238
min     5.000000   5.000000
25%     6.750000   9.000000
50%    10.000000  12.000000
75%    13.250000  13.250000
max    15.000000  15.000000

In [ ]:
#2. Carregue o dataset da url (https://www.kaggle.com/datasets/andrewmvd/global-monkeypox-cases)
    # Explore seu dataframe
    # Faça uma lista com todas as colunas disponíveis 
    # Veja todos os paises que tem no dataframe
    # Faça um groupby pais e veja quantos casos tem cada pais, gere um novo df com essa informação
    # Faça um groupby por status e pais e veja quantos casos confirmados tem por pais


In [46]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('monkeypox_df.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6500 entries, 0 to 6499
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       6499 non-null   float64
 1   Status                   6499 non-null   object 
 2   Location                 3775 non-null   object 
 3   City                     655 non-null    object 
 4   Country                  6499 non-null   object 
 5   Age                      1212 non-null   object 
 6   Gender                   1145 non-null   object 
 7   Date_onset               29 non-null     object 
 8   Date_confirmation        6108 non-null   object 
 9   Symptoms                 136 non-null    object 
 10  Hospitalised (Y/N/NA)    180 non-null    object 
 11  Date_hospitalisation     20 non-null     object 
 12  Isolated (Y/N/NA)        251 non-null    object 
 13  Date_isolation           14 non-null     object 
 14  Outcome                 

In [5]:
df.isnull().sum()

ID                            1
Status                        1
Location                   2725
City                       5845
Country                       1
Age                        5288
Gender                     5355
Date_onset                 6471
Date_confirmation           392
Symptoms                   6364
Hospitalised (Y/N/NA)      6320
Date_hospitalisation       6480
Isolated (Y/N/NA)          6249
Date_isolation             6486
Outcome                    6499
Contact_comment            6442
Contact_ID                 6487
Contact_location           6494
Travel_history (Y/N/NA)    6274
Travel_history_entry       6479
Travel_history_start       6495
Travel_history_location    6442
Travel_history_country     6445
Genomics_Metadata          6476
Confirmation_method        6404
Source                        1
Source_II                  4716
Date_entry                    2
Date_last_modified            2
Source_III                 6257
Source_IV                  6462
Country_

In [6]:
df.isnull().sum().sum()

146357

In [22]:
df.describe(include='all')

ID     Status Location    City Country    Age Gender  \
count   6499.000000       6499     3775     655    6499   1212   1145   
unique          NaN          4      349     152      82     52      3   
top             NaN  confirmed   Madrid  Madrid   Spain  15-74   Male   
freq            NaN       6106      714     121    1382    240   1128   
mean    3250.000000        NaN      NaN     NaN     NaN    NaN    NaN   
std     1876.244032        NaN      NaN     NaN     NaN    NaN    NaN   
min        1.000000        NaN      NaN     NaN     NaN    NaN    NaN   
25%     1625.500000        NaN      NaN     NaN     NaN    NaN    NaN   
50%     3250.000000        NaN      NaN     NaN     NaN    NaN    NaN   
75%     4874.500000        NaN      NaN     NaN     NaN    NaN    NaN   
max     6499.000000        NaN      NaN     NaN     NaN    NaN    NaN   

        Date_onset Date_confirmation               Symptoms  ...  \
count           29              6108                    136  ...   
unique          23                48                     54  ...   
top     2022-05-31        2022-06-30  genital ulcer lesions  ...   
freq             3               816                     30  ...   
mean           NaN               NaN                    NaN  ...   
std            NaN               NaN                    NaN  ...   
min            NaN               NaN                    NaN  ...   
25%            NaN               NaN                    NaN  ...   
50%            NaN               NaN                    NaN  ...   
75%            NaN               NaN                    NaN  ...   
max            NaN               NaN                    NaN  ...   

       Travel_history_country   Genomics_Metadata Confirmation_method  \
count                      55                  24                  96   
unique                     25                  11                   8   
top                     Spain  West African Clade              RT-PCR   
freq                       15                  13                  50   
mean                      NaN                 NaN                 NaN   
std                       NaN                 NaN                 NaN   
min                       NaN                 NaN                 NaN   
25%                       NaN                 NaN                 NaN   
50%                       NaN                 NaN                 NaN   
75%                       NaN                 NaN                 NaN   
max                       NaN                 NaN                 NaN   

                                                   Source  \
count                                                6499   
unique                                                510   
top     https://www.rki.de/DE/Content/InfAZ/A/Affenpoc...   
freq                                                  849   
mean                                                  NaN   
std                                                   NaN   
min                                                   NaN   
25%                                                   NaN   
50%                                                   NaN   
75%                                                   NaN   
max                                                   NaN   

                                                Source_II  Date_entry  \
count                                                1784        6498   
unique                                                282          42   
top     https://www.berlin.de/sen/wgpg/service/oft-ges...  2022-07-01   
freq                                                  435         709   
mean                                                  NaN         NaN   
std                                                   NaN         NaN   
min                                                   NaN         NaN   
25%                                                   NaN         NaN   
50%                                                   Na

In [11]:
df.describe()

ID   Contact_ID
count  6499.000000    13.000000
mean   3250.000000  1614.538462
std    1876.244032  1765.834157
min       1.000000     2.000000
25%    1625.500000   100.000000
50%    3250.000000  1125.000000
75%    4874.500000  1266.000000
max    6499.000000  4658.000000

In [8]:
df.head(10)

ID     Status                             Location       City   Country  \
0   1.0  confirmed  Guy's and St Thomas Hospital London     London   England   
1   2.0  confirmed  Guy's and St Thomas Hospital London     London   England   
2   3.0  confirmed                               London     London   England   
3   4.0  confirmed                               London     London   England   
4   5.0  confirmed                               London     London   England   
5   6.0  confirmed                               London     London   England   
6   7.0  confirmed                            Newcastle  Newcastle   England   
7   8.0  confirmed                               Lisbon     Lisbon  Portugal   
8   9.0  confirmed                               Lisbon     Lisbon  Portugal   
9  10.0  confirmed                               Lisbon     Lisbon  Portugal   

     Age Gender  Date_onset Date_confirmation  \
0    NaN    NaN  2022-04-29        2022-05-06   
1    NaN    NaN  2022-05-05        2022-05-12   
2    NaN    NaN  2022-04-30        2022-05-13   
3    NaN   Male         NaN        2022-05-15   
4    NaN   Male         NaN        2022-05-15   
5    NaN   Male         NaN        2022-05-15   
6    NaN   Male         NaN        2022-05-15   
7  20-44   Male         NaN        2022-05-17   
8  20-44   Male         NaN        2022-05-17   
9  20-44   Male         NaN        2022-05-17   

                           Symptoms  ... Travel_history_country  \
0                              rash  ...                Nigeria   
1                              rash  ...                    NaN   
2                    vesicular rash  ...                    NaN   
3                    vesicular rash  ...                    NaN   
4                    vesicular rash  ...                    NaN   
5                    vesicular rash  ...                    NaN   
6                    vesicular rash  ...                England   
7  skin lesions, ulcerative lesions  ...                    NaN   
8  skin lesions, ulcerative lesions  ...                    NaN   
9  skin lesions, ulcerative lesions  ...                    NaN   

    Genomics_Metadata Confirmation_method  \
0  West African Clade              RT-PCR   
1  West African Clade              RT-PCR   
2  West African Clade              RT-PCR   
3  West African Clade                 NaN   
4  West African Clade                 NaN   
5  West African Clade                 NaN   
6  West African Clade                 NaN   
7  West African Clade                 NaN   
8                 NaN                 NaN   
9                 NaN                 NaN   

                                              Source  \
0  https://www.gov.uk/government/news/monkeypox-c...   
1  https://www.gov.uk/government/news/monkeypox-c...   
2  https://www.gov.uk/government/news/monkeypox-c...   
3  https://www.gov.uk/government/news/monkeypox-c...   
4  https://www.gov.uk/government/news/monkeypox-c...   
5  https://www.gov.uk/government/news/monkeypox-c...   
6  https://www.gov.uk/government/news/monkeypox-c...   
7  https://cnnportugal.iol.pt/geral/portugal-tem-...   
8  https://cnnportugal.iol.pt/geral/portugal-tem-...   
9  https://cnnportugal.iol.pt/geral/portugal-tem-...   

                                           Source_II  Date_entry  \
0  https://www.who.int/emergencies/disease-outbre...  2022-05-18   
1                                                NaN  2022-05-18   
2                                                NaN  2022-05-18   
3                                                NaN  2022-05-18   
4                                                NaN  2022-05-18   
5                                                NaN  2022-05-18   
6                                                NaN  2022-05-18   
7                                                NaN  2022-05-18   
8                                                NaN  2022-05-18   
9                                                NaN 

In [18]:
# Faça uma lista com todas as colunas disponíveis
list(df.columns)

['ID',
 'Status',
 'Location',
 'City',
 'Country',
 'Age',
 'Gender',
 'Date_onset',
 'Date_confirmation',
 'Symptoms',
 'Hospitalised (Y/N/NA)',
 'Date_hospitalisation',
 'Isolated (Y/N/NA)',
 'Date_isolation',
 'Outcome',
 'Contact_comment',
 'Contact_ID',
 'Contact_location',
 'Travel_history (Y/N/NA)',
 'Travel_history_entry',
 'Travel_history_start',
 'Travel_history_location',
 'Travel_history_country',
 'Genomics_Metadata',
 'Confirmation_method',
 'Source',
 'Source_II',
 'Date_entry',
 'Date_last_modified',
 'Source_III',
 'Source_IV',
 'Country_ISO3']

In [20]:
# Veja todos os paises que tem no dataframe
df.Country.unique()

array(['England', 'Portugal', 'Spain', 'United States', 'Canada',
       'Sweden', 'Italy', 'France', 'Belgium', 'Australia', 'Germany',
       'Netherlands', 'Israel', 'Switzerland', 'Greece', 'Austria',
       'Argentina', 'Denmark', 'Morocco', 'Slovenia', 'Scotland',
       'Czech Republic', 'United Arab Emirates', 'Finland', 'Wales',
       'Northern Ireland', 'Sudan', 'Bolivia', 'Iran', 'Ecuador', 'Malta',
       'Ireland', 'Mexico', 'Pakistan', 'French Guiana', 'Thailand',
       'Peru', 'Brazil', 'Malaysia', 'Hungary', 'Norway', 'Paraguay',
       'Costa Rica', 'Gibraltar', 'Mauritius', 'Haiti', 'Uruguay',
       'Latvia', nan, 'Cayman Islands', 'Kosovo', 'Turkey', 'Bahamas',
       'Ghana', 'India', 'Iceland', 'Poland', 'Bangladesh', 'Uganda',
       'Cambodia', 'Malawi', 'Venezuela', 'Romania', 'Georgia',
       'Slovakia', 'Luxembourg', 'Nepal', 'Chile', 'Serbia', 'Lebanon',
       'South Korea', 'Singapore', 'South Africa', 'Taiwan', 'Colombia',
       'Croatia', 'Bulgaria',

In [34]:
pd.set_option('display.max_rows', None)
df_country = df.groupby('Country').ID.count().reset_index()
display(df_country)
pd.reset_option('^display.', silent = True)

Country    ID
0              Argentina     8
1              Australia    14
2                Austria    37
3                Bahamas     1
4             Bangladesh     1
5                Belgium   117
6                  Benin     3
7                Bolivia     3
8                 Brazil    74
9               Bulgaria     3
10              Cambodia    11
11                Canada   362
12        Cayman Islands     1
13                 Chile     7
14              Colombia     3
15            Costa Rica     1
16               Croatia     1
17        Czech Republic     8
18               Denmark    18
19               Ecuador     2
20               England  1185
21               Estonia     1
22                  Fiji     1
23               Finland     4
24                France   499
25         French Guiana     2
26               Georgia     1
27               Germany  1054
28                 Ghana    18
29             Gibraltar     1
30                Greece     4
31                 Haiti     1
32               Hungary    19
33               Iceland     4
34                 India     1
35                  Iran     6
36               Ireland    39
37                Israel    44
38                 Italy   201
39                Kosovo     1
40                Latvia     2
41               Lebanon     1
42            Luxembourg     3
43                Malawi     1
44              Malaysia     3
45                 Malta     4
46             Mauritius     3
47                Mexico    12
48               Morocco     4
49                 Nepal     1
50           Netherlands   257
51      Northern Ireland     6
52                Norway    17
53              Pakistan     1
54              Paraguay     1
55                  Peru     4
56                Poland    12
57              Portugal   402
58           Puerto Rico     1
59               Romania    11
60              Scotland    34
61                Serbia     1
62             Singapore     1
63              Slovakia     1
64              Slovenia     9
65               Somalia     3
66          South Africa     2
67           South Korea     2
68                 Spain  1382
69                 Sudan     1
70                Sweden    28
71           Switzerland    83
72                Taiwan     1
73              Thailand     9
74                Turkey     5
75                Uganda     6
76  United Arab Emirates    13
77         United States   395
78               Uruguay     4
79             Venezuela     1
80                 Wales    10
81                Zambia     1

In [35]:
df_country = df.groupby('Country').size().reset_index()
df_country


Country    0
0       Argentina    8
1       Australia   14
2         Austria   37
3         Bahamas    1
4      Bangladesh    1
..            ...  ...
77  United States  395
78        Uruguay    4
79      Venezuela    1
80          Wales   10
81         Zambia    1

[82 rows x 2 columns]

In [38]:
# Faça um groupby pais e veja quantos casos tem cada pais, gere um novo df com essa informação
df_cnt_stt = df.groupby(['Country', 'Status']).ID.count().reset_index()
df_cnt_stt[df_cnt_stt.Status == 'confirmed']

Country     Status    ID
0               Argentina  confirmed     6
2               Australia  confirmed    12
4                 Austria  confirmed    37
7                 Belgium  confirmed   117
8                   Benin  confirmed     3
11                 Brazil  confirmed    37
14               Bulgaria  confirmed     3
16                 Canada  confirmed   287
20                  Chile  confirmed     6
22               Colombia  confirmed     3
24                Croatia  confirmed     1
25         Czech Republic  confirmed     8
26                Denmark  confirmed    18
28                England  confirmed  1185
29                Estonia  confirmed     1
31                Finland  confirmed     4
32                 France  confirmed   498
35                Georgia  confirmed     1
36                Germany  confirmed  1054
37                  Ghana  confirmed    18
38              Gibraltar  confirmed     1
39                 Greece  confirmed     3
42                Hungary  confirmed    19
43                Iceland  confirmed     4
47                Ireland  confirmed    39
48                 Israel  confirmed    42
50                  Italy  confirmed   192
54                 Latvia  confirmed     2
55                Lebanon  confirmed     1
56             Luxembourg  confirmed     3
59                  Malta  confirmed     4
61                 Mexico  confirmed    11
63                Morocco  confirmed     1
66            Netherlands  confirmed   257
67       Northern Ireland  confirmed     6
68                 Norway  confirmed    17
71                   Peru  confirmed     3
73                 Poland  confirmed    12
74               Portugal  confirmed   402
75            Puerto Rico  confirmed     1
76                Romania  confirmed    11
77               Scotland  confirmed    34
78                 Serbia  confirmed     1
79              Singapore  confirmed     1
81               Slovenia  confirmed     9
83           South Africa  confirmed     2
84            South Korea  confirmed     1
86                  Spain  confirmed  1196
89                 Sweden  confirmed    28
90            Switzerland  confirmed    83
91                 Taiwan  confirmed     1
93                 Turkey  confirmed     1
96   United Arab Emirates  confirmed    13
97          United States  confirmed   395
100             Venezuela  confirmed     1
101                 Wales  confirmed    10

In [44]:
df_cnt_stt = df.groupby(['Country', 'Status']).ID.count().reset_index()
df_cnt_stt_pivot = df_cnt_stt.pivot(index='Country', columns='Status', values='ID')
df_cnt_stt_pivot

Status         confirmed  discarded  omit_error  suspected
Country                                                   
Argentina            6.0        NaN         2.0        NaN
Australia           12.0        NaN         2.0        NaN
Austria             37.0        NaN         NaN        NaN
Bahamas              NaN        1.0         NaN        NaN
Bangladesh           NaN        1.0         NaN        NaN
...                  ...        ...         ...        ...
United States      395.0        NaN         NaN        NaN
Uruguay              NaN        3.0         NaN        1.0
Venezuela            1.0        NaN         NaN        NaN
Wales               10.0        NaN         NaN        NaN
Zambia               NaN        NaN         NaN        1.0

[82 rows x 4 columns]

In [ ]:
#2. Carregue o dataset da url (https://www.kaggle.com/datasets/andrewmvd/global-monkeypox-cases)
    # Explore seu dataframe
    # Faça uma lista com todas as colunas disponíveis 
    # Veja todos os paises que tem no dataframe
    # Faça um groupby pais e veja quantos casos tem cada pais, gere um novo df com essa informação
    # Faça um groupby por status e pais e veja quantos casos confirmados tem por pais

In [ ]:
# NÃO PRECISA!!!! Inserir NaN nos null-values
df.Age = df.Age.fillna(np.nan)
df.Age

In [67]:
type(df.Age[0])

float

In [66]:
#   Separar as informações de uma única célula em duas: (i) lim inf e (ii) lim sup do range de cada valor
strip_Series = df.Age.apply(lambda x: x.split('-') if type(x) == str else x)
strip_Series
df['min_age'] = strip_Series.apply(lambda x: x[0] if type(x) == list else x)
df['max_age'] = strip_Series.apply(lambda x: x[1] if type(x) == list else x)
df

ID     Status                             Location       City  \
0        1.0  confirmed  Guy's and St Thomas Hospital London     London   
1        2.0  confirmed  Guy's and St Thomas Hospital London     London   
2        3.0  confirmed                               London     London   
3        4.0  confirmed                               London     London   
4        5.0  confirmed                               London     London   
...      ...        ...                                  ...        ...   
6495  6495.0  confirmed                     Balearic Islands        NaN   
6496  6496.0  confirmed                     Balearic Islands        NaN   
6497  6497.0  confirmed                   Castilla la Mancha        NaN   
6498  6498.0  confirmed                            Cantabria        NaN   
6499  6499.0  confirmed                                Ceara  Fortaleza   

      Country    Age Gender  Date_onset Date_confirmation        Symptoms  \
0     England    NaN    NaN  2022-04-29        2022-05-06            rash   
1     England    NaN    NaN  2022-05-05        2022-05-12            rash   
2     England    NaN    NaN  2022-04-30        2022-05-13  vesicular rash   
3     England    NaN   Male         NaN        2022-05-15  vesicular rash   
4     England    NaN   Male         NaN        2022-05-15  vesicular rash   
...       ...    ...    ...         ...               ...             ...   
6495    Spain    NaN    NaN         NaN        2022-06-30             NaN   
6496    Spain    NaN    NaN         NaN        2022-06-30             NaN   
6497    Spain    NaN    NaN         NaN        2022-06-30             NaN   
6498    Spain    NaN    NaN         NaN        2022-06-30             NaN   
6499   Brazil  35-39    NaN         NaN        2022-06-29             NaN   

      ... Confirmation_method  \
0     ...              RT-PCR   
1     ...              RT-PCR   
2     ...              RT-PCR   
3     ...                 NaN   
4     ...                 NaN   
...   ...                 ...   
6495  ...                 NaN   
6496  ...                 NaN   
6497  ...                 NaN   
6498  ...                 NaN   
6499  ...                 NaN   

                                                 Source  \
0     https://www.gov.uk/government/news/monkeypox-c...   
1     https://www.gov.uk/government/news/monkeypox-c...   
2     https://www.gov.uk/government/news/monkeypox-c...   
3     https://www.gov.uk/government/news/monkeypox-c...   
4     https://www.gov.uk/government/news/monkeypox-c...   
...                                                 ...   
6495  https://www.sanidad.gob.es/en/profesionales/sa...   
6496  https://www.sanidad.gob.es/en/profesionales/sa...   
6497  https://www.sanidad.gob.es/en/profesionales/sa...   
6498  https://www.sanidad.gob.es/en/profesionales/sa...   
6499  https://g1.globo.com/ce/ceara/noticia/2022/06/...   

                                              Source_II  Date_entry  \
0     https://www.who.int/emergencies/disease-outbre...  2022-05-18   
1                                                   NaN  2022-05-18   
2                                                   NaN  2022-05-18   
3                                                   NaN  2022-05-18   
4                                                   NaN  2022-05-18   
...                                                 ...         ...   
6495                                                NaN  2022-07-01   
6496                                                NaN  2022-07-01   
6497                                                NaN  2022-07-01   
6498                                                NaN  2022-07-01   
6499                                                NaN  2022-07-01   

     Date_last_modified Source_III  Source_IV Country_ISO3 min_age max_age  
0            2022-05-18        NaN        NaN          GBR     NaN     NaN  
1            2022-05-18        NaN        NaN          GBR     NaN     

In [69]:
display(df.min_age.unique())
display(df.max_age.unique())

array([nan, '20', '30', '40', '25', '50', '35', '15', '55', '45', '10',
       '70', '60', '65', '26', '5', '22', '0', '34', '19'], dtype=object)

array([nan, '44', '59', '29', '34', '64', '49', '39', '74', '19', '24',
       '50', '54', '14', '69', '45', '9', '55', '5', '42', '40', '46',
       '62', '125', '60'], dtype=object)

In [ ]:
#3 Opcional(vamos discutir em aula)
    # O que vocês fariam com a coluna Idade?
    # R: Realizar algum tipo de tratamento
    #   Inserir NaN nos null-values
    #   Separar as informações em lim inf e lim sup do range de cada valor

    # Faça o tratamento de acordo com a sua linha de pensamento
    
    # Esse tratamento que fez é útil (Sim / Não e Por que)?
    # Mais ou menos, fica mais fácil de estimar se determinado caso pode estar no intervalo, mas para por aí
    
    # O que podemos fazer com essa informação para ter um dado mais acertivo?